# Didgen by YangHaitao

# log level
# a value of (DEBUG, INFO, WARN, ERROR)
log_level: INFO
log_path: logs

# host and port that you will use other device to request this service
server_host: 0.0.0.0
server_port: 6389

# how many threads you want to run goroutines
threads: 5

# data path, default is Didgen/data
data_path: data

# batch size
batch_size: 5000