# Didgen by YangHaitao

# log level
# a value of (DEBUG, INFO, WARN, ERROR)
log_level: INFO
log_path: logs

# host and port that you will use other device to request this service
server_host: 0.0.0.0
server_port: 6389
trans_port: 6089
server_id: 0

nodes:
    - server_host: 127.0.0.1
      server_port: 6390
      trans_port: 6090
    - server_host: 127.0.0.1
      server_port: 6391
      trans_port: 6091

heartbeat_time_out: 10
heartbeat_time_interval: 5

# how many threads you want to run goroutines
threads: 5

# data path, default is Didgen/data
data_path: data

# batch size
batch_size: 5000